//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMOSHIRO.Views.Dashboard
{


    public partial class Store
    {

        /// <summary>
        /// Featured control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OMOSHIRO.Views.Dashboard.UC.Featured Featured;

        /// <summary>
        /// RackLayout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OMOSHIRO.Views.Dashboard.UC.RackLayout RackLayout;

        /// <summary>
        /// GridLayout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OMOSHIRO.Views.Dashboard.UC.GridLayout GridLayout;
    }
}
